name: CustomBanUI
main: SaltyPixelDevz\CustomBanUI\Ban
version: 1.0.0
api: 3.0.0
author: SaltyPixelDevz
website: saltypixel.ga
commands:
 banish:
  description: "Opens the Staff Banish UI"
  permission: banui.use